### PR TITLE
PHP 7 + TYPO3 7.6 Support

### PR DESCRIPTION
**Pull request by sascha-seyfert**
Env: PHP 7.0.0 and TYPO3 7.6 LTS.
Fix error on extension activation.

### CODE REVIEW

**Comment by freshp** [comment]
:thumbsup:

**Comment by bittner** [comment]
@dmitryd Any plans merging this PR?

**Comment by dmitryd** [comment]
Yes, I plan to work on sentry soon and will add support for 7.6 and 8.7.

**Comment by dmitryd** [comment]
Thanks! I merged without testing because I plan to update the ext now.

**Pull request merged**
